
- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  pre_tasks:
    - name: Update packages on Debian/Ubuntu
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: latest
      when: ansible_pkg_mgr == 'apt'
      tags:
        - update

    - name: Update packages on non-apt systems
      become: yes
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: yes  # This option is specific to yum/dnf
      when: (ansible_pkg_mgr == 'yum') or (ansible_pkg_mgr == 'dnf')
      tags:
        - update

    - name: Update packages on brew
      become: yes
      ansible.builtin.package:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'homebrew'
      tags:
        - update

  tasks:
    - include_tasks: tasks/terminal.yml
    - include_tasks: tasks/core-software.yml
    - include_tasks: tasks/tools.yml
    - include_tasks: tasks/icons.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/dotfiles.yml

