
- name: Install system packages and log
  become: yes
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - pkg-config
    - libpthread-stubs0-dev
    - libtool
    - libtool-bin
    - gettext
    - lua5.4
  loop_control:
    loop_var: item
  when: ansible_pkg_mgr == 'apt'
  register: package_installation_result

- name: Log package installation status
  debug:
    msg: "Package '{{ item }}' installation status: {{ item.status }}"
  with_items: "{{ package_installation_result.results }}"
  when: ansible_pkg_mgr == 'apt'



- name: Generic system packages
  become: yes
  ansible.builtin.package:
    name: ["cmake", "lolcat", "exa", "bat", "curl", "htop", "tree", "unzip", "python3", "fzf", "fd-find", "ripgrep", "stow", "parallel", "expect"]


- name: Red hat system packages
  become: yes
  ansible.builtin.package:
    name: ["lua"]
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

