- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Sam-Hobson/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
  tags:
    - dotfiles


# TODO: Add or detect different versions

# - name: Stow dotfiles
#   shell: cd $HOME/.dotfiles && ./fedora
