- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Sam-Hobson/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master


# TODO: Add or detect different versions

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./fedora
