
- name: Create (/usr/share/icons/myCustomIcons/) if it doesn't exist
  become: yes
  file:
    path: "/usr/share/icons/myCustomIcons"
    state: directory
  when: "'Linux' in ansible_system"
  tags:
    - linux
    - icons
    - bitwarden


- name: Bitwarden icon
  become: yes
  get_url:
    url: https://github.com/bitwarden/brand/blob/master/icons/128x128.png?raw=true
    dest: /usr/share/icons/myCustomIcons/bitwarden.png
    mode: '0755'
  when: "'Linux' in ansible_system"
  tags:
    - linux
    - bitwarden


