
- name: Install neovim
  become: yes
  ansible.builtin.package:
    name: "neovim"


- name: Install packer
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"


- name: Neovim Plugin Development 1
  become: yes
  ansible.builtin.package:
    name: luarocks


- name: Neovim Plugin Development 2 luacheck
  become: yes
  shell: luarocks install luacheck

