# TODO: Add fira-code and sauce code pro nerd fonts download


- name: Setup kitty terminal emulator
  become: true
  ansible.builtin.package:
    name: "kitty"
    state: present
  tags:
    - system
    - term

- name: Download zsh
  become: yes
  ansible.builtin.package:
    name: "zsh"
    state: present
  tags:
    - term
    - shell

- name: Make zsh default shell (reboot required)
  become: yes
  shell: chsh -s $(which zsh)
  tags:
    - term
    - shell

