# TODO: Chrome


- name: Installing extra packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - wireshark
    - xclip
    - exa
    - bat
    - firefox
    - tmux
  tags:
    - tools

- name: Create ripgrep auto-completion directory
  ansible.builtin.file:
    path: ~/.oh-my-zsh/custom/plugins/ripgrep/src/
    state: directory
  tags:
    - ripgrep
    - tools

- name: Create ripgrep auto-completion
  shell:
    cmd: $(which rg) --generate=complete-zsh > ~/.oh-my-zsh/custom/plugins/ripgrep/src/_ripgrep
    executable: /bin/sh
  tags:
    - ripgrep
    - tools

- name: Create ripgrep auto-completion basic config file
  blockinfile:
    path: ~/.oh-my-zsh/custom/plugins/ripgrep/ripgrep.plugin.zsh
    block: |
      fpath+="${0:A:h}/src"
    create: yes
  tags:
    - ripgrep
    - tools


# Bitwarden (for linux)
- name: Download Bitwarden (may or may not be in path)
  become: yes
  get_url:
    url: https://vault.bitwarden.com/download/?app=desktop&platform=linux
    dest: /usr/bin/bitwarden
    mode: '0755'
  when: "'Linux' in ansible_system"
  tags:
    - bitwarden
    - linux

- name: Check if application profile exists
  become: yes
  stat:
    path: /usr/share/applications/bitwarden.desktop
  register: bitwarden_path
  when: "'Linux' in ansible_system"
  tags:
    - bitwarden
    - linux

- name: Add Bitwarden application profile
  become: yes
  blockinfile:
    path: /usr/share/applications/bitwarden.desktop
    block: |
      [Desktop Entry]
      Name=Bitwarden
      GenericName=Password Manager
      Comment=Manage your passwords
      Exec=bitwarden
      Icon=/usr/share/icons/myCustomIcons/bitwarden.png
      Terminal=false
      Type=Application
      Keywords=password;
    create: yes
  when: "'Linux' in ansible_system and not bitwarden_path.stat.exists"
  tags:
    - bitwarden
    - linux
